version: '3.5'

services:
  mysql:
    image: mysql:8.0.25
    container_name: mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      edu-net:
        ipv4_address: 172.28.0.10
    environment:
      #设置root帐号密码
      MYSQL_ROOT_PASSWORD: testMysql
    ports:
      - 3306:3306
    volumes:
      #/var/run/mysqld/mysqld.pid
      #数据文件挂载
      - /mnt/volume/mysql/data:/var/lib/mysql
      #配置文件挂载
      - /mnt/volume/mysql/conf:/etc/mysql/conf.d
      #日志文件挂载
      - /mnt/volume/mysql/logs:/var/log/mysql
    # /etc/sysctl.conf
    sysctls:
      ####aliyun
      # see details in https://help.aliyun.com/knowledge_detail/39428.html
      net.ipv4.conf.default.rp_filter: 0
      net.ipv4.conf.all.rp_filter: 0
      net.ipv4.conf.eth0.rp_filter: 0
      net.ipv4.conf.default.arp_announce: 2
      net.ipv4.conf.all.arp_announce: 2
      # see details in https://help.aliyun.com/knowledge_detail/41334.html
      net.ipv4.tcp_synack_retries: 2
      net.ipv4.tcp_fin_timeout: 60
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv6.conf.default.disable_ipv6: 1
      net.ipv6.conf.lo.disable_ipv6: 1
      # 时间戳可以避免序列号的卷绕。一个 1Gbps 的链路肯定会遇到以前用过的序列号。时间戳能够让内核接受这种“异常” 的数据包。这里需要将其关掉
      net.ipv4.tcp_timestamps: 0
      #该参数设置系统的 TIME_WAIT 的数量，如果超过默认值则会被立即清除
      net.ipv4.tcp_max_tw_buckets: 20000
      #定义了系统中每一个端口最大的监听队列的长度，这是个全局的参数
      net.core.somaxconn: 65535
      #对于还未获得对方确认的连接请求，可保存在队列中的最大数目
      net.ipv4.tcp_max_syn_backlog: 262144
      #防火墙跟踪表的大小。注意：如果防火墙没开则会提示error: "net.netfilter.nf_conntrack_max" is an unknown key，忽略即可
      net.netfilter.nf_conntrack_max: 2621440
    # /etc/security/limits.conf
    ulimits:
      core: 655350
      nproc: 655350
      nofile: 655350

  redis:
    image: redis:5.0.12
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      edu-net:
        ipv4_address: 172.28.0.20
    ports:
      - 6379:6379
    volumes:
      #/var/run/redis_6379.pid
      #数据文件挂载
      - /mnt/volume/redis/data:/data
      #配置文件挂载
      - /mnt/volume/redis/conf:/usr/local/etc/redis
    # /etc/sysctl.conf
    sysctls:
      ####aliyun
      # see details in https://help.aliyun.com/knowledge_detail/39428.html
      net.ipv4.conf.default.rp_filter: 0
      net.ipv4.conf.all.rp_filter: 0
      net.ipv4.conf.eth0.rp_filter: 0
      net.ipv4.conf.default.arp_announce: 2
      net.ipv4.conf.all.arp_announce: 2
      # see details in https://help.aliyun.com/knowledge_detail/41334.html
      net.ipv4.tcp_synack_retries: 2
      net.ipv4.tcp_fin_timeout: 60
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv6.conf.default.disable_ipv6: 1
      net.ipv6.conf.lo.disable_ipv6: 1
      # 时间戳可以避免序列号的卷绕。一个 1Gbps 的链路肯定会遇到以前用过的序列号。时间戳能够让内核接受这种“异常” 的数据包。这里需要将其关掉
      net.ipv4.tcp_timestamps: 0
      #该参数设置系统的 TIME_WAIT 的数量，如果超过默认值则会被立即清除
      net.ipv4.tcp_max_tw_buckets: 20000
      #定义了系统中每一个端口最大的监听队列的长度，这是个全局的参数
      net.core.somaxconn: 65535
      #对于还未获得对方确认的连接请求，可保存在队列中的最大数目
      net.ipv4.tcp_max_syn_backlog: 262144
      #防火墙跟踪表的大小。注意：如果防火墙没开则会提示error: "net.netfilter.nf_conntrack_max" is an unknown key，忽略即可
      net.netfilter.nf_conntrack_max: 2621440
    # /etc/security/limits.conf
    ulimits:
      core: 655350
      nproc: 655350
      nofile: 655350


#docker network ls
#The actual name is volume_edu-net
#表示新建了 `172.28.0.0/16` 的网络，名称为 edu-net
#新建网络是为了实现同主机的多个容器间网络互通，走内网，类似于软件交换机
networks:
  edu-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16