langyastudio:
  task:
    fixedDelaySchedule: 60000
  disk:
    local:
      root: /mnt/volume/edu/pms/
      #只有在windows运行时才生效
      #use for test on windows OS
      win-root: Z:/volume/edu/pms/
      #文件存储路径
      root-file: ${langyastudio.disk.local.root}file/
      #转码路径自动映射为mts/
      root-mts: ${langyastudio.disk.local.root}mts/
      #文件存储临时路径
      root-tmp: ${langyastudio.disk.local.root}temp/upload/
      #-图片-可直接浏览的文件大小10M
      browse-img-max-size: 10485760
      #-图片-可转码的文件大小20M
      cvt-img-max-size: 20971520
      # 最大文件大小，默认10M
      max-size: 10485760
      # 是否允许空文件:
      allow-empty: false
      # 允许的文件类型:
      allow-types: jpg, png, gif

server:
  # 服务端口
  port: ${APP_PORT:8080}
  # 错误页，指定发生错误时，跳转的URL
  error:
    path: /error
  # 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败，只有特殊需求的情况下才配置
  # address=192.168.0.6
  servlet:
    # spring 2.x 中文乱码
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://192.168.123.22:3306/edu_account
    username: root
    password: Hacfin_Mysql8
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 1
      max-wait: 6000
      #pool-prepared-statements:
      #max-pool-prepared-statement-per-connection-size:
      validation-query: SELECT 1
      #validation-query-timeout:
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #max-evictable-idle-time-millis:
      filters: wall

  redis:
    host: 192.168.123.22
    port: 6379
    password: Hacfin_Redis8
    timeout: 6000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: 10000ms
        # 最大空闲
        max-idle: 8
        # 最小空闲
        min-idle: 0
      #cluster:       # 集群配置
      #nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
      #max-redirects: 2  # 最大重定向次数

  servlet:
    # 开启文件上传
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

  task:
    scheduling:
      pool:
        size: 5
      shutdown:
        #关闭应用程序时，是否等待任务执行完毕
        await-termination: true
        await-termination-period: 60000

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations:
    classpath*:mapper/*.xml

  configuration:
    auto-mapping-behavior: partial
    # 开启驼峰命名
    map-underscore-to-camel-case: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      # 表名前缀
      table-prefix:

  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true

#actuator
info:
  name: spring boot app
  version: 1.0.1
  maintainer: langyastudio
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        #health, info
        include: health, info, beans, env, conditions, httptrace, configprops, threaddump, loggers, mappings, metrics

      #修改访问地址
      #base-path: /monitor
      #path-mapping:
      #  health: check-health
